apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      hostNetwork: true
      containers:
      - name: consumer
        image: 192.168.5.177:5000/python
        imagePullPolicy: Always
        command: ["python3", "consumer_script.py"]
  minReadySeconds: 5