apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: 192.168.5.177:5000/kafka
        imagePullPolicy: Always
        command: ["/kafka_2.13-2.8.0/bin/kafka-server-start.sh"]
        args:
          - "/kafka_2.13-2.8.0/config/server.properties"
          - "--override"
          - "listeners=PLAINTEXT://:9092"
          - "--override"
          - "advertised.listeners=PLAINTEXT://192.168.5.142:30092"  # Ensure this is the IP you want to expose
          - "--override"
          - "zookeeper.connect=192.168.5.142:32404"
        ports:
        - containerPort: 9092
      nodeSelector:
        kubernetes.io/hostname: t13vm2  # Ensures deployment on t13vm2

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30092