apiVersion: batch/v1
kind: Job
metadata:
  name: producer-job
spec:
  completions: 4
  parallelism: 4
  template:
    metadata:
      labels:
        app: producer
    spec:
      hostNetwork: true
      restartPolicy: Never
      containers:
      - name: producer
        image: 192.168.5.177:5000/python
        env:
        - name: PRODUCER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command: ["python3", "producer_script.py"]
        imagePullPolicy: Always